#!/bin/bash

echo "Checking if Docker is installed..."
if ! command -v docker &> /dev/null
then
    echo "Docker not found, installing Docker..."
    sudo amazon-linux-extras enable docker
    sudo yum install -y docker
    sudo systemctl start docker
    sudo systemctl enable docker
    sudo usermod -a -G docker ec2-user
else
    echo "Docker is already installed."
fi

echo "Docker installation completed."
